북마크편집기 구현(addFolder, addLink, buildTree, relocateFolder, removeFolder, removeLink)
play-your-bookmark/bookmark-frontend pull request #2
Opened 2022-02-04 16:05 UTC by Hyunwooksuh

- 북마크 편집기 중 시각화를 제외하고, nestedArray build method 및 기타 메소드를 추가하였음
- 카테고리 설정 등 시각화 추가 구현예정

2022-02-04 16:26 UTC, shlee39 approved these changes

2022-02-04 16:26 UTC, shlee39 commented on src/utils/tree.js
> +      if (FOLDERS[i]['parent_folder'] === parentId) {
쌍따옴표로 통일!
```suggestion
      if (FOLDERS[i]["parent_folder"] === parentId) {
```

2022-02-05 03:40 UTC, hatae94 requested changes

2022-02-05 03:40 UTC, hatae94 commented on src/redux/store/store.js
> +export default store;
```suggestion
export default store;

```
마지막 줄 개행이 있어야할 것 같습니다!

2022-02-05 05:17 UTC, hatae94 requested changes

2022-02-05 05:17 UTC, hatae94 commented on src/utils/api.js
> +export default req;
개행만 추가하면 될 것 같습니다~

2022-02-05 05:17 UTC, hatae94 commented on src/utils/folders.json
> +]
여기도 개행만 하면 될 것 같아요!

2022-02-05 05:34 UTC, merged