Feat: 추가 treeview 구현 및 redux 사용하여 nested Array 구성
play-your-bookmark/bookmark-frontend pull request #8
Opened 2022-02-07 13:48 UTC by Hyunwooksuh

# [Frontend][53] Feat: 추가 treeview 구현 및 redux 사용하여 nested Array 구성
## Jira 칸반 링크

- https://90crew.atlassian.net/browse/MYS-53?atlOrigin=eyJpIjoiNjM0ZTM5N2M4YzJkNDk3N2JkYzlmYWQxOGI2NzRlNDIiLCJwIjoiaiJ9

## 카드에서 구현 혹은 해결하려는 내용
- 재귀 rendering을 통해 nested array를 render함 
- mock data 삭제 후 redux store 에서 my_created_folder fetch 후, nested tree를 빌드함

## 테스트 방법
- npm start
- 트리계층구조별로 rendering 됨 확인. redux logger 확인 완료
## 기타 사항
- 추가적으로 Drag and drop으로 연결 필요

2022-02-07 15:28 UTC, hatae94 requested changes
현욱님 수고하셨습니다!

이해가 부족했었는데 이번 리뷰를 통해
드래그 앤 드롭과 트리뷰 구현 로직의 전반적인 흐름을 알 수 있었습니다.
특별한 문제는 없어보이고 제안드린 부분만 수정되면 좋을 것 같습니다!

감사합니다~

2022-02-07 15:28 UTC, hatae94 commented on src/utils/tree.js
> +  for (let i = 1; i < folderList.length; i++) {
```suggestion

  for (let i = 1; i < folderList.length; i++) {
```
for문과 변수 할당 사이에 개행해주시면 좋을 것 같습니다!

2022-02-07 15:37 UTC, shlee39 approved these changes
멋지게 구현해주셨군요... 감사합니다! 바로 dnd까지 무사히 연결시키겠습니다.
고생 많으셨습니다!

2022-02-08 02:17 UTC, Hyunwooksuh commented on src/utils/tree.js
> +  for (let i = 1; i < folderList.length; i++) {
개행완료했습니다! 감사합니다~

2022-02-08 02:59 UTC, hatae94 approved these changes

2022-02-08 03:23 UTC, merged